"""Remove a matriz redundante de permissões."""
from collections.abc import Sequence

from alembic import op

revision: str = "0022_remove_permission_matrix"
down_revision: str | None = "0021_merge_schema_heads"
branch_labels: Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("DROP TABLE IF EXISTS permission_matrix")


def downgrade() -> None:
    op.execute(
        """CREATE TABLE IF NOT EXISTS permission_matrix (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            matrix JSONB NOT NULL DEFAULT '{}'::jsonb,
            role VARCHAR(40),
            can_view_projects BOOLEAN NOT NULL DEFAULT TRUE,
            can_create_projects BOOLEAN NOT NULL DEFAULT FALSE,
            can_edit_projects BOOLEAN NOT NULL DEFAULT FALSE,
            can_delete_projects BOOLEAN NOT NULL DEFAULT FALSE,
            can_manage_members BOOLEAN NOT NULL DEFAULT FALSE,
            can_upload_files BOOLEAN NOT NULL DEFAULT FALSE,
            can_delete_files BOOLEAN NOT NULL DEFAULT FALSE,
            can_approve_requests BOOLEAN NOT NULL DEFAULT FALSE
        )"""
    )
