"use client"

import { useMemo, useState } from "react"
import useSWR from "swr"
import { Clock3, Download, Files, FolderKanban, FolderOpen, Search, ShieldCheck, Users } from "lucide-react"
import { ExportButton, ExportFieldsDialog, type ExportField } from "@/components/export-fields-dialog"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { downloadFile, getAccessMap, getAccessMapExportUrl, getCatalogs, getReportFields } from "@/lib/api-client"
import type { AccessMapResponse } from "@/lib/types"
import { PetrobrasLoading } from "@/components/petrobras-loading"
import { KpiCards, type KpiItem } from "@/components/dashboard/kpi-cards"
import { PageHeader, PageLayout, PageSection } from "@/components/shared/page-layout"

const fetcher = () => getAccessMap()
const dateFormat = new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" })
function safeDate(value?: string | null) { if (!value) return "Não informado"; const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? "Não informado" : dateFormat.format(parsed) }

export default function PesquisasPage() {
  const { data, error, isLoading } = useSWR<AccessMapResponse>("access-map", fetcher)
  const { data: catalogs } = useSWR("platform-catalogs", getCatalogs)
  const { data: configuredFields } = useSWR("/api/report-fields?report_code=acessos", () => getReportFields("acessos"))
  const [search, setSearch] = useState(""); const [type, setType] = useState("todos"); const [level, setLevel] = useState("todos"); const [area, setArea] = useState("todos"); const [view, setView] = useState("projeto"); const [exportOpen, setExportOpen] = useState(false)
  const exportFields: ExportField[] = (configuredFields?.fields ?? []).map((field) => ({ key: field.field_key, label: field.label }))
  const rows = useMemo(() => (data?.rows ?? []).filter((row) => { const text = `${row.userName} ${row.userEmail} ${row.projectName} ${row.resourceName}`.toLowerCase(); return text.includes(search.toLowerCase()) && (type === "todos" || row.resourceType === type) && (level === "todos" || row.accessLevel === level) && (area === "todos" || row.area === area) }), [data?.rows, search, type, level, area])
  const clearFilters = () => { setSearch(""); setType("todos"); setLevel("todos"); setArea("todos"); setView("projeto") }
  const exportRows = async (fields: string[], formats: ("csv" | "txt" | "pdf")[]) => { for (const format of formats) { const path = getAccessMapExportUrl({ format, fields: fields.join(","), q: search, type, level, view }).replace(/^https?:\/\/[^/]+/, ""); const blob = await downloadFile(path); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `mapa-de-acessos.${format}`; link.click(); URL.revokeObjectURL(url) } }
  if (isLoading) return <PageLayout back><PageHeader title="Mapa de acessos" description="Consulte as relações de acesso autorizadas." /><PetrobrasLoading label="Carregando mapa de acessos..." /></PageLayout>
  if (error || !data) return <PageLayout back><PageHeader title="Mapa de acessos" /><p className="text-destructive">Não foi possível carregar o mapa de acessos.</p></PageLayout>
  const cards: KpiItem[] = [
    { icon: Users, label: "Usuários no escopo", value: String(data.summary.users), tone: "teal" }, { icon: FolderKanban, label: "Projetos", value: String(data.summary.projects), tone: "green" }, { icon: FolderOpen, label: "Pastas", value: String(data.summary.folders), tone: "blue" }, { icon: Files, label: "Arquivos", value: String(data.summary.files), tone: "yellow" },
  ]
  return <PageLayout back>
    <PageHeader eyebrow="Governança de acesso" title="Mapa de acessos científicos" description="Pesquise a cadeia de acesso por pessoa, projeto e recurso em uma visão pronta para auditoria." actions={<ExportButton onClick={() => setExportOpen(true)} disabled={!exportFields.length} />} />
    <div className="flex flex-wrap items-center gap-3 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1.5"><span className="size-2 rounded-full bg-petrobras-green" />Fonte: {data.source}</span><span>Atualizado em {safeDate(data.consultedAt)}</span></div>
    <PageSection label="Panorama do escopo"><KpiCards items={cards} /></PageSection>
    <Card className="overflow-hidden border-petrobras-blue/15 shadow-sm"><CardHeader className="border-b border-border/70 bg-gradient-to-r from-petrobras-green/8 via-background to-petrobras-yellow/10"><div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between"><div><div className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.16em] text-petrobras-green"><ShieldCheck className="size-4" />Pesquisa de permissões</div><CardTitle>Relações de acesso</CardTitle><CardDescription className="mt-1">Cruze filtros e encontre rapidamente quem possui acesso a cada recurso.</CardDescription></div><Badge variant="outline" className="w-fit bg-background/70">{rows.length} relações</Badge></div>
      <div className="grid gap-3 pt-2 md:grid-cols-2 lg:grid-cols-[minmax(240px,1.5fr)_repeat(3,minmax(150px,1fr))]"><div className="relative"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground" /><Input className="bg-background/80 pl-9" placeholder="Usuário, projeto ou recurso" value={search} onChange={(e) => setSearch(e.target.value)} /></div><Select value={type} onValueChange={(value) => setType(value ?? "todos")}><SelectTrigger><SelectValue placeholder="Tipo de recurso" /></SelectTrigger><SelectContent><SelectItem value="todos">Todos os recursos</SelectItem><SelectItem value="pasta">Pastas</SelectItem><SelectItem value="arquivo">Arquivos</SelectItem></SelectContent></Select><Select value={area} onValueChange={(value) => setArea(value ?? "todos")}><SelectTrigger><SelectValue placeholder="Área responsável" /></SelectTrigger><SelectContent><SelectItem value="todos">Todas as áreas</SelectItem>{(catalogs?.areas ?? []).map((item) => <SelectItem key={item.id} value={item.nome}>{item.nome}</SelectItem>)}</SelectContent></Select><Select value={level} onValueChange={(value) => setLevel(value ?? "todos")}><SelectTrigger><SelectValue placeholder="Nível de acesso" /></SelectTrigger><SelectContent><SelectItem value="todos">Todos os níveis</SelectItem><SelectItem value="leitura">Leitura</SelectItem><SelectItem value="edicao">Edição</SelectItem><SelectItem value="gerente">Gerente</SelectItem><SelectItem value="participante">Participante</SelectItem></SelectContent></Select></div>
      <div className="flex flex-wrap items-center gap-2 pt-1"><Button variant={view === "projeto" ? "secondary" : "outline"} size="sm" onClick={() => setView("projeto")}>Visão por projeto</Button><Button variant={view === "usuario" ? "secondary" : "outline"} size="sm" onClick={() => setView("usuario")}>Visão por usuário</Button><Button variant="ghost" size="sm" onClick={clearFilters}>Limpar filtros</Button><span className="text-xs text-muted-foreground">A exportação usará este recorte</span></div>
    </CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-muted/45 text-left text-xs uppercase tracking-wide text-muted-foreground"><tr><th className="px-6 py-3 font-medium">Usuário</th><th className="px-4 py-3 font-medium">Projeto</th><th className="px-4 py-3 font-medium">Recurso</th><th className="px-4 py-3 font-medium">Acesso</th><th className="px-4 py-3 font-medium">Última visualização</th></tr></thead><tbody className="divide-y divide-border/60">{rows.map((row) => <tr key={`${row.userId}-${row.resourceId}`} className="transition-colors hover:bg-petrobras-green/5"><td className="px-6 py-4"><p className="font-semibold">{row.userName}</p><p className="text-xs text-muted-foreground">{row.userEmail || "E-mail não informado"}</p></td><td className="px-4 py-4"><p>{row.projectName}</p><p className="font-mono text-xs text-muted-foreground">{row.projectId}</p></td><td className="px-4 py-4"><div className="flex items-center gap-2"><span className="size-2 rounded-full bg-petrobras-teal" />{row.resourceName}<span className="text-xs text-muted-foreground">({row.resourceType})</span></div></td><td className="px-4 py-4"><Badge variant={row.accessLevel === "gerente" ? "default" : "secondary"}>{row.accessLevel}</Badge></td><td className="px-4 py-4 text-muted-foreground"><span className="flex items-center gap-2 whitespace-nowrap"><Clock3 className="size-4" />{safeDate(row.lastViewedAt)}</span></td></tr>)}</tbody></table></div>{!rows.length && <p className="px-6 py-12 text-center text-sm text-muted-foreground">Nenhuma relação encontrada para os filtros selecionados.</p>}<div className="flex flex-wrap items-center justify-between gap-3 border-t border-border/70 px-6 py-4 text-xs text-muted-foreground"><span>Exibindo {rows.length} relações autorizadas</span><span className="inline-flex items-center gap-2"><Download className="size-3.5" />Exportação filtrada disponível no cabeçalho</span></div></CardContent></Card>
    <ExportFieldsDialog open={exportOpen} onOpenChange={setExportOpen} title="mapa de acessos" fields={exportFields} onConfirm={exportRows} />
  </PageLayout>
}
