-- SIGAC / Aurora PostgreSQL
-- DDL completo do banco novo. Execute antes de 002_inserts_completos.sql.
\set ON_ERROR_STOP on
BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE schema_migrations (version varchar(120) PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE profiles (id varchar(20) PRIMARY KEY, name varchar(80) NOT NULL UNIQUE, description varchar(255) NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE users (id varchar(255) PRIMARY KEY, name varchar(200) NOT NULL, email varchar(320) NOT NULL UNIQUE, job_title varchar(120), area varchar(120), role varchar(40) NOT NULL DEFAULT 'solicitante', profile_id varchar(20) REFERENCES profiles(id) ON DELETE SET NULL, avatar_url varchar(500), last_login_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE modules (id varchar(80) PRIMARY KEY, name varchar(120) NOT NULL UNIQUE, route varchar(180) NOT NULL DEFAULT '', icon varchar(80) NOT NULL DEFAULT 'folder', display_order integer NOT NULL DEFAULT 0, active boolean NOT NULL DEFAULT true);
CREATE TABLE permissions (id varchar(80) PRIMARY KEY, module_id varchar(80) NOT NULL REFERENCES modules(id) ON DELETE CASCADE, name varchar(120) NOT NULL, description text NOT NULL DEFAULT '', active boolean NOT NULL DEFAULT true);
CREATE TABLE profile_permissions (profile_id varchar(20) NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, permission_id varchar(80) NOT NULL REFERENCES permissions(id) ON DELETE CASCADE, allowed boolean NOT NULL DEFAULT true, PRIMARY KEY (profile_id, permission_id));
CREATE TABLE profile_modules (profile_id varchar(20) NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, module_id varchar(80) NOT NULL REFERENCES modules(id) ON DELETE CASCADE, can_view boolean NOT NULL DEFAULT true, PRIMARY KEY (profile_id, module_id));
CREATE TABLE menus (id varchar(80) PRIMARY KEY, module_id varchar(80) REFERENCES modules(id) ON DELETE SET NULL, parent_id varchar(80), name varchar(120) NOT NULL, route varchar(180) NOT NULL DEFAULT '', icon varchar(80) NOT NULL DEFAULT 'circle', display_order integer NOT NULL DEFAULT 0, active boolean NOT NULL DEFAULT true);
CREATE TABLE menu_permissions (menu_id varchar(80) NOT NULL REFERENCES menus(id) ON DELETE CASCADE, permission_id varchar(80) NOT NULL REFERENCES permissions(id) ON DELETE CASCADE, allowed boolean NOT NULL DEFAULT true, PRIMARY KEY (menu_id, permission_id));
CREATE TABLE project_statuses (id varchar(40) PRIMARY KEY, code varchar(40) NOT NULL UNIQUE, name varchar(100) NOT NULL, color varchar(20) NOT NULL DEFAULT 'slate', display_order integer NOT NULL DEFAULT 0, active boolean NOT NULL DEFAULT true, allows_edit boolean NOT NULL DEFAULT true);
CREATE TABLE project_types (id varchar(40) PRIMARY KEY, code varchar(40) NOT NULL UNIQUE, name varchar(100) NOT NULL, description text NOT NULL DEFAULT '', active boolean NOT NULL DEFAULT true);
CREATE TABLE responsible_areas (id varchar(40) PRIMARY KEY, name varchar(160) NOT NULL UNIQUE, prefix varchar(20) NOT NULL UNIQUE, next_number integer NOT NULL DEFAULT 1, active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE system_settings (key varchar(120) PRIMARY KEY, value text NOT NULL DEFAULT '', value_type varchar(30) NOT NULL DEFAULT 'string', description text NOT NULL DEFAULT '', group_name varchar(80) NOT NULL DEFAULT 'general', active boolean NOT NULL DEFAULT true);
CREATE TABLE report_types (id varchar(60) PRIMARY KEY, code varchar(60) NOT NULL UNIQUE, name varchar(120) NOT NULL, description text NOT NULL DEFAULT '', formats text NOT NULL DEFAULT 'csv,txt,pdf', active boolean NOT NULL DEFAULT true);
CREATE TABLE report_fields (id varchar(60) PRIMARY KEY, report_code varchar(60) NOT NULL REFERENCES report_types(code) ON DELETE CASCADE, field_key varchar(100) NOT NULL, label varchar(160) NOT NULL, source_key varchar(160) NOT NULL, display_order integer NOT NULL DEFAULT 0, active boolean NOT NULL DEFAULT true, UNIQUE (report_code, field_key));
CREATE TABLE dashboard_cards (id varchar(80) PRIMARY KEY, module_id varchar(80) REFERENCES modules(id) ON DELETE SET NULL, key varchar(80) NOT NULL UNIQUE, title varchar(140) NOT NULL, description text NOT NULL DEFAULT '', metric_key varchar(80) NOT NULL, route varchar(180) NOT NULL DEFAULT '', profile_ids text NOT NULL DEFAULT '', display_order integer NOT NULL DEFAULT 0, active boolean NOT NULL DEFAULT true);
CREATE TABLE projects (id varchar(36) PRIMARY KEY, name varchar(200) NOT NULL, code varchar(50) NOT NULL UNIQUE, responsible_area varchar(160) NOT NULL, managers_ids jsonb NOT NULL DEFAULT '[]', write_group varchar(160) NOT NULL DEFAULT '', read_group varchar(160) NOT NULL DEFAULT '', write_identity_role varchar(160) NOT NULL DEFAULT '', read_identity_role varchar(160) NOT NULL DEFAULT '', snow_task_number varchar(120) NOT NULL DEFAULT '', parent_folder varchar(500) NOT NULL DEFAULT '', description text NOT NULL DEFAULT '', status varchar(30) NOT NULL DEFAULT 'ativo', participants_ids jsonb NOT NULL DEFAULT '[]', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE project_members (project_id varchar(36) NOT NULL REFERENCES projects(id) ON DELETE CASCADE, user_id varchar(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE, role varchar(40), created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY (project_id, user_id));
CREATE TABLE folders (id varchar(36) PRIMARY KEY, project_id varchar(36) NOT NULL REFERENCES projects(id) ON DELETE CASCADE, parent_id varchar(36) REFERENCES folders(id) ON DELETE CASCADE, kind varchar(20) NOT NULL DEFAULT 'pasta' CHECK (kind = 'pasta'), name varchar(500) NOT NULL, size_bytes bigint NOT NULL DEFAULT 0, mime_type varchar(160), created_by varchar(255) NOT NULL REFERENCES users(id) ON DELETE RESTRICT, last_viewed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE access_requests (id varchar(36) PRIMARY KEY, project_id varchar(36) NOT NULL REFERENCES projects(id) ON DELETE CASCADE, requester_id varchar(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE, status varchar(30) NOT NULL, request_type varchar(40), requested_role varchar(40), justification text, servicenow_ticket varchar(120), analyzed_by varchar(255) REFERENCES users(id) ON DELETE SET NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE activity_logs (id varchar(36) PRIMARY KEY, user_id varchar(255) REFERENCES users(id) ON DELETE SET NULL, action varchar(100) NOT NULL, entity varchar(100) NOT NULL, entity_id varchar(36), details text NOT NULL DEFAULT '', result varchar(40), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE sessions (id varchar(128) PRIMARY KEY, user_id varchar(255), email varchar(320) NOT NULL, display_name varchar(255), profile_id varchar(20) REFERENCES profiles(id) ON DELETE RESTRICT, expires_at timestamp NOT NULL, created_at timestamp NOT NULL DEFAULT current_timestamp);

CREATE INDEX idx_users_email ON users(email); CREATE INDEX idx_projects_status ON projects(status); CREATE INDEX idx_project_members_user ON project_members(user_id); CREATE INDEX idx_folders_project_parent ON folders(project_id,parent_id); CREATE INDEX idx_activity_logs_created ON activity_logs(created_at DESC); CREATE INDEX idx_access_requests_project ON access_requests(project_id); CREATE INDEX idx_sessions_user ON sessions(user_id); CREATE INDEX idx_sessions_expires ON sessions(expires_at); CREATE INDEX idx_report_fields_code ON report_fields(report_code);
COMMIT;
