-- SIGAC / Aurora PostgreSQL
-- Seeds completos e idempotentes. Execute após 001_estrutura_completa.sql.
\set ON_ERROR_STOP on
BEGIN;

INSERT INTO profiles (id,name,description,created_at) VALUES
('ADM','administrador','Administra a plataforma, configura parâmetros e gerencia acessos.',now()),('GER','gerente','Coordena projetos, equipes e atividades operacionais.',now()),('AUD','auditor','Consulta informações e acompanha registros de auditoria.',now()),('PAT','patrocinador','Acompanha resultados e aprova solicitações.',now()),('SOL','solicitante','Solicita acessos e acompanha solicitações.',now()) ON CONFLICT (id) DO UPDATE SET name=excluded.name,description=excluded.description;

-- Usuários técnicos de desenvolvimento; autenticação e senha são gerenciadas pelo CAV4.
INSERT INTO users (id,name,email,job_title,area,role,profile_id) VALUES
('seed-admin','Administrador de Desenvolvimento','admin.dev@sigac.local','Administrador','Governança e Compliance','administrador','ADM'),
('seed-gerente','Gerente de Desenvolvimento','gerente.dev@sigac.local','Gerente de Projetos','Tecnologia','gerente','GER'),
('seed-auditor','Auditor de Desenvolvimento','auditor.dev@sigac.local','Auditor','Auditoria','auditor','AUD')
ON CONFLICT (id) DO UPDATE SET name=excluded.name, email=excluded.email, job_title=excluded.job_title, area=excluded.area, role=excluded.role, profile_id=excluded.profile_id;

INSERT INTO modules (id,name,route,icon,display_order) VALUES
('projetos','Projetos','/projetos','folder',10),('relatorios','Relatórios','/relatorios','chart',30),('auditoria','Logs e Auditoria','/logs','history',50),('pesquisas','Mapa de Acessos','/pesquisas','search',60),('configuracoes','Configurações','/configuracoes','settings',70) ON CONFLICT(id) DO UPDATE SET name=excluded.name,route=excluded.route,icon=excluded.icon,display_order=excluded.display_order,active=true;
INSERT INTO permissions (id,module_id,name,description) VALUES
('projeto.visualizar','projetos','Visualizar projetos','Visualizar projetos'),('projeto.criar','projetos','Criar projetos','Criar projetos'),('projeto.editar','projetos','Editar projetos','Editar projetos'),('projeto.status','projetos','Alterar status','Alterar status de projetos'),('projeto.excluir','projetos','Excluir projetos','Excluir projetos'),('relatorio.visualizar','relatorios','Visualizar relatórios','Visualizar relatórios'),('relatorio.exportar','relatorios','Exportar relatórios','Exportar CSV, TXT e PDF'),('auditoria.visualizar','auditoria','Visualizar auditoria','Visualizar logs de auditoria'),('pesquisa.visualizar','pesquisas','Visualizar mapa de acessos','Consultar projetos, grupos, membros, pastas e níveis'),('administracao.configurar','configuracoes','Configurar administração','Editar módulos, menus, permissões, perfis e relatórios') ON CONFLICT(id) DO UPDATE SET module_id=excluded.module_id,name=excluded.name,description=excluded.description,active=true;
INSERT INTO menus (id,module_id,name,route,icon,display_order) VALUES
('menu-dashboard',NULL,'Dashboard','/dashboard','layout-dashboard',1),('menu-projetos','projetos','Projetos','/projetos','folder',10),('menu-relatorios','relatorios','Relatórios','/relatorios','chart',30),('menu-auditoria','auditoria','Logs e Auditoria','/logs','history',50),('menu-pesquisas','pesquisas','Mapa de Acessos','/pesquisas','search',60),('menu-configuracoes','configuracoes','Configurações','/configuracoes','settings',70) ON CONFLICT(id) DO UPDATE SET module_id=excluded.module_id,name=excluded.name,route=excluded.route,icon=excluded.icon,display_order=excluded.display_order,active=true;
INSERT INTO menu_permissions(menu_id,permission_id) VALUES ('menu-projetos','projeto.visualizar'),('menu-relatorios','relatorio.visualizar'),('menu-auditoria','auditoria.visualizar'),('menu-pesquisas','pesquisa.visualizar'),('menu-configuracoes','administracao.configurar') ON CONFLICT DO NOTHING;
INSERT INTO project_statuses(id,code,name,color,display_order) VALUES ('ativo','ativo','Ativo','green',10),('em-implantacao','em_implantacao','Em implantação','blue',20),('pausado','pausado','Pausado','amber',30),('encerrado','encerrado','Encerrado','slate',40) ON CONFLICT(id) DO UPDATE SET name=excluded.name,color=excluded.color,display_order=excluded.display_order,active=true;
INSERT INTO project_types(id,code,name,description) VALUES ('cientifico','cientifico','Científico','Projeto científico'),('administrativo','administrativo','Administrativo','Projeto administrativo') ON CONFLICT(id) DO UPDATE SET name=excluded.name,description=excluded.description,active=true;
INSERT INTO responsible_areas(id,name,prefix,next_number) VALUES ('tecnologia','Tecnologia','TEC',1),('pesquisa','Pesquisa','PES',1),('engenharia','Engenharia','ENG',1),('operacoes','Operações','OP',1),('governanca-compliance','Governança e Compliance','GC',1),('documentacao','Documentação','DOC',1) ON CONFLICT(id) DO UPDATE SET name=excluded.name,prefix=excluded.prefix,active=true;
INSERT INTO report_types(id,code,name,description,formats) VALUES ('PROJETOS','projetos','Relatório Executivo de Projetos','Portfólio, status, áreas, gestores e indicadores.','csv,txt,pdf'),('ACESSOS','acessos','Mapa de Acessos Científico','Projetos, grupos, membros, pastas e níveis de acesso.','csv,txt,pdf'),('AUDITORIA','auditoria','Logs de Auditoria','Rastreabilidade de ações, usuários, entidades e resultados.','csv,txt,pdf') ON CONFLICT(id) DO UPDATE SET code=excluded.code,name=excluded.name,description=excluded.description,formats=excluded.formats,active=true;
INSERT INTO report_fields(id,report_code,field_key,label,source_key,display_order) VALUES
('projetos-codigo','projetos','codigo','Código','codigo',10),('projetos-nome','projetos','nome','Projeto','nome',20),('projetos-area','projetos','areaResponsavel','Área responsável','areaResponsavel',30),('projetos-status','projetos','status','Status','status',40),('projetos-gestores','projetos','gestoresIds','Gestores','gestoresIds',50),('projetos-membros','projetos','totalMembros','Total de membros','totalMembros',60),('projetos-criado','projetos','criadoEm','Criado em','criadoEm',70),('projetos-atualizado','projetos','atualizadoEm','Atualizado em','atualizadoEm',80),
('acessos-usuario-id','acessos','userId','Identificador do usuário','userId',10),('acessos-usuario','acessos','userName','Membro','userName',20),('acessos-email','acessos','userEmail','E-mail','userEmail',30),('acessos-perfil','acessos','userRole','Perfil','userRole',40),('acessos-area','acessos','area','Área','area',50),('acessos-projeto-id','acessos','projectId','Identificador do projeto','projectId',60),('acessos-projeto','acessos','projectName','Projeto','projectName',70),('acessos-status','acessos','projectStatus','Status do projeto','projectStatus',80),('acessos-recurso','acessos','resourceName','Recurso','resourceName',90),('acessos-tipo','acessos','resourceType','Tipo de recurso','resourceType',100),('acessos-atualizacao','acessos','lastViewedAt','Último acesso','lastViewedAt',110),
('auditoria-id','auditoria','id','Identificador','id',10),('auditoria-data','auditoria','criadoEm','Data e hora','criadoEm',20),('auditoria-usuario','auditoria','userName','Usuário','userName',30),('auditoria-email','auditoria','userEmail','E-mail','userEmail',40),('auditoria-acao','auditoria','acao','Ação','acao',50),('auditoria-entidade','auditoria','entidade','Entidade','entidade',60),('auditoria-entidade-id','auditoria','entidadeId','Identificador da entidade','entidadeId',70),('auditoria-resultado','auditoria','resultado','Resultado','resultado',80),('auditoria-detalhes','auditoria','detalhes','Detalhes','detalhes',90) ON CONFLICT(id) DO UPDATE SET report_code=excluded.report_code,field_key=excluded.field_key,label=excluded.label,source_key=excluded.source_key,display_order=excluded.display_order,active=true;
INSERT INTO dashboard_cards(id,module_id,key,title,description,metric_key,route,profile_ids,display_order) VALUES ('dashboard-projetos','projetos','projetos','Projetos','Projetos disponíveis no seu escopo.','total_projetos','/projetos','ADM,GER,AUD,PAT',10),('dashboard-pendencias','relatorios','pendencias','Pendências','Itens que precisam de atenção.','pendencias','/relatorios','ADM,GER,PAT',20),('dashboard-auditoria','auditoria','auditoria','Auditoria','Eventos recentes para acompanhamento.','eventos_auditoria','/logs','ADM,AUD',30) ON CONFLICT(key) DO UPDATE SET module_id=excluded.module_id,title=excluded.title,description=excluded.description,metric_key=excluded.metric_key,route=excluded.route,profile_ids=excluded.profile_ids,active=true;
INSERT INTO profile_modules(profile_id,module_id,can_view) SELECT p.id,m.id,CASE WHEN p.id='ADM' THEN true WHEN m.id='configuracoes' THEN false WHEN m.id='auditoria' THEN p.id IN('AUD','ADM') WHEN m.id IN('relatorios','pesquisas') THEN p.id IN('GER','AUD','PAT','ADM') ELSE p.id IN('GER','AUD','PAT','ADM') END FROM profiles p CROSS JOIN modules m ON CONFLICT(profile_id,module_id) DO UPDATE SET can_view=excluded.can_view;
INSERT INTO profile_permissions(profile_id,permission_id,allowed) SELECT p.id,x.permission_id,CASE WHEN p.id='ADM' THEN true WHEN x.permission_id='projeto.visualizar' THEN p.id IN('GER','AUD','PAT') WHEN x.permission_id='relatorio.visualizar' THEN p.id IN('GER','AUD','PAT') WHEN x.permission_id='relatorio.exportar' THEN p.id IN('ADM','GER') WHEN x.permission_id='auditoria.visualizar' THEN p.id IN('ADM','AUD') WHEN x.permission_id='pesquisa.visualizar' THEN p.id IN('ADM','GER','AUD','PAT') ELSE false END FROM profiles p CROSS JOIN (VALUES ('projeto.visualizar'),('projeto.criar'),('projeto.editar'),('projeto.status'),('projeto.excluir'),('relatorio.visualizar'),('relatorio.exportar'),('auditoria.visualizar'),('pesquisa.visualizar'),('administracao.configurar')) x(permission_id) ON CONFLICT(profile_id,permission_id) DO UPDATE SET allowed=excluded.allowed;
INSERT INTO schema_migrations(version) VALUES ('database_consolidado_v1') ON CONFLICT DO NOTHING;
COMMIT;
