-- Schema SQLite canônico para desenvolvimento e testes locais.
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS perfis (id TEXT PRIMARY KEY, nome TEXT NOT NULL UNIQUE, descricao TEXT DEFAULT '', criado_em TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS modulos (id TEXT PRIMARY KEY, nome TEXT NOT NULL UNIQUE, rota TEXT NOT NULL DEFAULT '', icone TEXT NOT NULL DEFAULT 'folder', ordem INTEGER NOT NULL DEFAULT 0, ativo INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS permissoes (id TEXT PRIMARY KEY, modulo_id TEXT NOT NULL REFERENCES modulos(id), nome TEXT NOT NULL, descricao TEXT NOT NULL DEFAULT '', ativo INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS perfil_permissoes (perfil_id TEXT NOT NULL REFERENCES perfis(id) ON DELETE CASCADE, permissao_id TEXT NOT NULL REFERENCES permissoes(id) ON DELETE CASCADE, permitido INTEGER NOT NULL DEFAULT 1, PRIMARY KEY (perfil_id, permissao_id));
CREATE TABLE IF NOT EXISTS perfil_modulos (perfil_id TEXT NOT NULL REFERENCES perfis(id) ON DELETE CASCADE, modulo_id TEXT NOT NULL REFERENCES modulos(id) ON DELETE CASCADE, pode_visualizar INTEGER NOT NULL DEFAULT 1, PRIMARY KEY (perfil_id, modulo_id));
CREATE TABLE IF NOT EXISTS status_projetos (id TEXT PRIMARY KEY, codigo TEXT NOT NULL UNIQUE, nome TEXT NOT NULL, cor TEXT NOT NULL DEFAULT 'slate', ordem INTEGER NOT NULL DEFAULT 0, ativo INTEGER NOT NULL DEFAULT 1, permite_edicao INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS tipos_projetos (id TEXT PRIMARY KEY, codigo TEXT NOT NULL UNIQUE, nome TEXT NOT NULL, descricao TEXT NOT NULL DEFAULT '', ativo INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS configuracoes_sistema (chave TEXT PRIMARY KEY, valor TEXT NOT NULL DEFAULT '', tipo TEXT NOT NULL DEFAULT 'string', descricao TEXT NOT NULL DEFAULT '', grupo TEXT NOT NULL DEFAULT 'geral', ativo INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS tipos_relatorios (id TEXT PRIMARY KEY, codigo TEXT NOT NULL UNIQUE, nome TEXT NOT NULL, descricao TEXT NOT NULL DEFAULT '', formatos TEXT NOT NULL DEFAULT 'csv', ativo INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS report_types (id TEXT PRIMARY KEY, code TEXT NOT NULL UNIQUE, name TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', formats TEXT NOT NULL DEFAULT 'csv', active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS report_fields (id TEXT PRIMARY KEY, report_code TEXT NOT NULL REFERENCES report_types(code) ON DELETE CASCADE, field_key TEXT NOT NULL, label TEXT NOT NULL, source_key TEXT NOT NULL, display_order INTEGER NOT NULL DEFAULT 0, active INTEGER NOT NULL DEFAULT 1, UNIQUE (report_code, field_key));
CREATE TABLE IF NOT EXISTS menus (id TEXT PRIMARY KEY, modulo_id TEXT REFERENCES modulos(id), parent_id TEXT, nome TEXT NOT NULL, rota TEXT NOT NULL DEFAULT '', icone TEXT NOT NULL DEFAULT 'circle', ordem INTEGER NOT NULL DEFAULT 0, ativo INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS groups (id TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE, description TEXT DEFAULT '', created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS user_groups (user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, group_id TEXT NOT NULL REFERENCES groups(id) ON DELETE CASCADE, source TEXT NOT NULL DEFAULT 'manual', created_at TEXT NOT NULL, PRIMARY KEY (user_id, group_id));
CREATE TABLE IF NOT EXISTS project_members (project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, papel TEXT NOT NULL, created_at TEXT NOT NULL, PRIMARY KEY (project_id, user_id));
CREATE TABLE IF NOT EXISTS project_groups (project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE, group_id TEXT NOT NULL REFERENCES groups(id) ON DELETE CASCADE, papel TEXT NOT NULL, created_at TEXT NOT NULL, PRIMARY KEY (project_id, group_id));
CREATE TABLE IF NOT EXISTS file_permissions (file_id TEXT NOT NULL REFERENCES files(id) ON DELETE CASCADE, user_id TEXT REFERENCES users(id) ON DELETE CASCADE, group_id TEXT REFERENCES groups(id) ON DELETE CASCADE, nivel TEXT NOT NULL, inherited_from TEXT, created_at TEXT NOT NULL, CHECK (user_id IS NOT NULL OR group_id IS NOT NULL));
CREATE INDEX IF NOT EXISTS idx_user_groups_group ON user_groups(group_id);
CREATE INDEX IF NOT EXISTS idx_project_groups_group ON project_groups(group_id);
CREATE INDEX IF NOT EXISTS idx_file_permissions_file ON file_permissions(file_id);
